KILTprotocol/sdk-js

docs/getting-started.md

removed claimer : sdk.Contact since the method only needs 2 parameters and the encrypted Message contains the claimers Public Key

removed deprecated parameter for createFromEncryptedMessage

---

src/messaging/Message.ts

IMessage now has optional parameter senderboxpublickey. Should resolve the failed build.

fix: decrypted message has to support senderboxpublickey

---

.eslintrc.json
package.json
yarn.lock

This PR adds eslint rules for jsdoc.
- I didn't add `require-hyphen-before-param-description`, because it would exclude the possibility to have the descriptions starting on a newline.
- I also excluded `require-jsdoc`, because it can't check for private methods, where I wouldn't want to enforce jsdocs
- I didn't set the rules to `error`, because nobody would be able to commit anymore, since the existing jsdocs don't follow these rules and the plugin maintainer uses `warn` himself. We can think of using `error` later.
What do you think about these three things?
- Make a jsdoc
- Try different jsdoc variations
- always check against eslint (either via `yarn lint`, or eslint plugin of your IDE)

docs: add eslint rules for jsdoc

---

.eslintrc-jsdoc.json
.eslintrc.json
package.json
src/blockchainApiConnection/index.ts
src/crypto/index.ts
src/ctype/CType.chain.ts
src/ctype/CTypeSchema.ts
src/ctype/CTypeUtils.ts
src/delegation/Delegation.chain.ts
src/delegation/DelegationNode.chain.ts
src/delegation/DelegationNode.utils.ts
src/delegation/DelegationRootNode.chain.ts
src/did/Did.chain.ts
src/did/Did.utils.ts
src/identity/PublicIdentity.ts
src/types/Attestation.ts
src/types/AttestedClaim.ts
src/types/CType.ts
src/types/Claim.ts
src/types/Delegation.ts
src/types/PublicIdentity.ts
src/types/RequestForAttestation.ts
yarn.lock

This PR adds eslint rules for `@example` directives in jsdoc.
It also updates `tsdoc`, so that the examples are displayed properly.
Write an `@example` in your jsdoc.
It should look like this:
````
@example ```javascript
const bla = 'keks';
``` 
````

docs: add eslint rules for examples in jsdoc

---

src/ctype/CType.spec.ts
src/ctype/CTypeUtils.ts

Removed funtions from the CtypeUtils, and placed them into the demo-client. 
yarn test
Test Suites: 1 skipped, 17 passed, 17 of 18 total
Tests:       2 skipped, 49 passed, 51 total

refactor: removed ctype utils to the demo client

---

src/ctype/CType.chain.ts

`getOwner(ctype.hash)` internally was receiving an empty result
```    
encoded Type [Uint8Array] [
0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0
] 
```
when the CType hash did not exist on chain, but this was converted to a public address by the decoder, which was then returned by `getOwner()`. With this fix, `decode()` returns `null` for an empty result and `getOwner()` returns `null` when the ctype hash is not found on chain. 
`await getOwner('0x22b14646c541790db1e2879c93302c5e6872476cb2212c0665b0ca78e9ca2ee1')`
must return `null`

fix: empty address was decoded to string representation

---

src/did/Did.spec.ts
src/did/Did.ts
src/did/Did.utils.ts

- Added a signature property to the generated Did Document and a verification utility method 
- Created dedicated interfaces
- Made sure to create both static and non-static versions of the new methods
`yarn test`

Feat: added signature/verification features to the DID Document methods

---

src/attestation/Attestation.spec.ts
src/attestation/Attestation.ts
src/attestedclaim/AttestedClaim.spec.ts
src/requestforattestation/RequestForAttestation.spec.ts

The delegation id was not taken from the `RequestForAttestation`, but a new parameter. This is unnecessary, since it is already included there.
This also did break the demo-client.
- Make a delegation tree and make an attestation with that
- Look at the chain-explorer to see the inclusion of the delegation id in the attestation, which is written on-chain

fix: take delegationId from request

---

.github/workflows/tests.yml

This PR uses the devnet node for the integration tests
See github actions

ci: use latest devnet for integration tests

---

src/__integrationtests__/Attestation.spec.ts
src/__integrationtests__/Ctypes.spec.ts
src/__integrationtests__/Delegation.spec.ts
src/__integrationtests__/Did.spec.ts
src/attestation/Attestation.spec.ts
src/balance/Balance.spec.ts
src/delegation/Delegation.spec.ts
src/delegation/DelegationNode.spec.ts
src/delegation/DelegationRootNode.spec.ts
src/did/Did.spec.ts
src/identity/PublicIdentity.spec.ts

fixes https://github.com/KILTprotocol/ticket/issues/304
Option return values are introduced in KILTprotocol/mashnet-node#78
This change set is compatible with the current SDK. This PR just updates the mocked return values to reflect that objects of type `Option` are returned in most `api.query.` calls to ensure they accurately reflect the behaviour of the actual mashnet node.
`yarn test`

test: updating unit tests to use Option return values

---

src/__integrationtests__/Attestation.spec.ts
src/__integrationtests__/Balance.spec.ts
src/__integrationtests__/Ctypes.spec.ts
src/__integrationtests__/Delegation.spec.ts
src/__integrationtests__/utils.ts

Refactorings on the assumption that Alice and Bob are endowed identities on the dev chain, thus eliminating the need to transfer money to them when two token holding identities are required for a test.
run integration tests with a mashnet dev node that incorporates the changes introduced by https://github.com/KILTprotocol/mashnet-node/pull/79

test: refactoring tests for alice & bob w/ tokens

---

src/ctype/CType.spec.ts
src/ctype/CType.utils.ts

Currently compress throws an Error when given a ctype with owner set to null, even though `CType['owner']` is of union type `IPublicIdentity['address'] | null`
It should instead check, if the owner is a valid address or null
checking with checkAddress from '@polkadot/util-crypto' and prefix 42

fix: ctype compress accepts nulled owner

---

src/__integrationtests__/Attestation.spec.ts
src/__integrationtests__/Balance.spec.ts
src/__integrationtests__/ChainConnectivity.spec.ts
src/__integrationtests__/Ctypes.spec.ts
src/__integrationtests__/Delegation.spec.ts
src/blockchain/Blockchain.spec.ts
src/blockchain/Blockchain.ts
src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts

Returns a map of strings instead of Codec types from `getStats()`.
Adds unit tests to verify this behaviour in the future. 
(new) unit tests and integration tests should cover it.

refactor: chain stats return string types

---

src/errorhandling/ExtrinsicError.spec.ts
src/errorhandling/ExtrinsicError.ts

- `errorsByCode` in [ExtrinsicError.ts](https://github.com/KILTprotocol/sdk-js/blob/0c219d9ea268fecd1a4d926e2621d55a5f267dec/src/errorhandling/ExtrinsicError.ts#L131) was an array of length 3101 ([Playground Link](https://www.typescriptlang.org/play/?ssl=151&ssc=1&pln=1&pc=1#))
- changed `errorsByCode` to be an object
- fixed typo in former ExtrinsicError `ERROR_AL(R)EADY_ATTESTED`
- added documentation to `errorsByCode` and `errorForCode`
- added jest tests which check whether
- all ExtrinsicErrors are inside `errorsForCode`
- `errorForCode` returns an ExtrinsicError for each `errorCode`
```bash
yarn test ExtrinsicError
```

Fix ExtrinsicError array of length 3101

---

src/identity/Identity.spec.ts
src/identity/Identity.ts
src/identity/PublicIdentity.ts

- fixed that `Identity.getPublicIdentity()` did not return an instance of `PublicIdentity`
- added a test
- fixed two minor documentation errors
```bash
yarn jest -t "should return instanceof PublicIdentity" Identity
```

Fix: getPublicIdentity should be instanceof PublicIdentity

---

docs/example.ts
src/messaging/Message.spec.ts
src/messaging/Message.ts

- `message.**getEncryptedMessage**` -> `message.**encrypt**`
- `Kilt.Message.**createFromEncryptedMessage**` -> `Kilt.Message.**decrypt**`
- include `Kilt.Message.ensureHashAndSignature` and `Kilt.Message.ensureOwnerIsSender` in `decrypt`
- add destructuring to parameters to emphasize what properties are needed from `Kilt.Message` 
- refactor `IEncryptedMessage` to "extend" `IMessage` without "hardcoding" the properties seperately
- add documentation
- add testing for errors of `ensureHashAndSignature` and `ensureOwnerIsSender`
```
yarn test Message
```

refactor: messaging

---

src/attestation/Attestation.ts
src/attestation/Attestation.utils.ts
src/attestedclaim/AttestedClaim.utils.ts
src/claim/Claim.ts
src/claim/Claim.utils.ts
src/ctype/CType.utils.ts
src/ctype/CTypeMetadata.ts
src/delegation/DelegationNode.ts
src/delegation/DelegationRootNode.ts
src/did/Did.ts
src/did/Did.utils.ts
src/errorhandling/ErrorHandler.ts
src/identity/Identity.ts
src/messaging/Message.ts
src/quote/Quote.ts
src/quote/Quote.utils.ts
src/requestforattestation/RequestForAttestation.ts
src/requestforattestation/RequestForAttestation.utils.ts

Improves the jsdoc coverage and adds @throw tags to all functions that throw errors, this branch is based on lw-154-constructor-checks, as this adds a lot of Error throwing functions.
Please provide feedback for the added documentation and request away!
Should the throw tags only represent the Errors the function explicitly throws or should we add the called functions thrown Errors too, especially in the case of our own verify functions, called mostly to check objects? @tjwelde

Doc: Add @throws #369

---

src/actor/Attester.spec.ts
src/actor/Claimer.spec.ts
src/actor/Verifier.spec.ts
src/attestation/Attestation.spec.ts
src/delegation/Delegation.spec.ts
src/delegation/DelegationRootNode.spec.ts

Replaced Data/Text with appropriate H256 type when mocking blockchain return values to better represent the actual chain behaviour and to prevent faulty decoding.

test: appropriate mocking hash type

---

src/blockchainApiConnection/BlockchainApiConnection.ts
src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts

The Blockchain connection can be retrieved from cache and is stored in the variable instance.
The Code creates full instances but returns Interface only, I changed the retrun type to better represent the code behaviour.

fix: blockchain cache returns instance

---

src/ctype/CTypeSchema.ts

This PR gets the required fields from the ctype schema and adds it in the schema section of the wrapper schema. Before that, some fields were not marked as required.
- Tests should run
- Making a ctype and using it to make a claim in demo-client has to be possible
- To test, cherry-pick this commit onto sdk master branch and use it in the demo-client

feat: required fields in ctype wrapper schema

---

.github/workflows/devpackpublish.yml
.npmrc

Builds and publishes the sdk as a npm package to the GitHub Packages repo.
These releases are versioned with the current commit id and tagged `dev`.
Possible issues:
- removed it after talking to Dudley, who added it
- does not seem to interfere
By adding this branch to the triggers I have successfully triggered a release. You can find the published package in https://github.com/KILTprotocol/sdk-js/packages/286306.

feat: publishing to github packages from develop

---

src/config/ConfigLog.spec.ts
src/config/ConfigLog.ts

Changes the default logLevel from Debug to Error, with the option to enable Debug mode with env variable DEBUG.
Adds new exported function to change the logLevel of all factories to the specified level.
start with or without DEBUG env set to true, call modifyLogLevel, see many logs or not.

Feat: Debug mode and modify logLevel

---

src/kilt/Kilt.ts

Changes the return type of Kilt default `connect` function, as the `getCached` returns the full instance now

chore: changed return type of connect function

---

src/attestation/Attestation.ts

Adds static as well as class method for retrieving the rootNode from the delegationId supplied with Attestation

feat: added query of delegation root id

---

src/errorhandling/SDKErrors.ts

The Demo-client complains and does not compile with the way we destructure the parameter array.

fix: pe-verification error parameter

---

.github/workflows/devpackpublish.yml

- adds dispatch action to workflow after publishing the github package
- see [here](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event) for more general information
- this action can be received from the workshop and triggers the CI tests there (this is the only trigger!)
- In the workshop:
- automatically creates an issue when the CI breaks there + links the SDK commit sha
- see the updated KILT workshop CI [here](https://github.com/KILTprotocol/kilt-workshop-101/commit/5b73041fba422c6dcb81b9e50f453d3ea7c2c741) 
```
on:
repository_dispatch:
types: [sdk-update]
```
Can only check after we merged this PR. However, I tested this locally on a dummy repo until it worked.

chore: add dispatch event to workflow

---

src/actor/Claimer.spec.ts
src/actor/Claimer.ts
src/credential/Credential.ts
src/errorhandling/SDKErrors.ts
src/identity/AttesterIdentity.ts
src/identity/Identity.ts
src/index.ts
src/messaging/Message.ts
src/requestforattestation/RequestForAttestation.ts

This PR adds options to methods to disable calls to portablegabi, so that the wasm file is not loaded.
- Tests should run

feat: option for disabling gabi

---

.eslintrc.json
docs/example.ts
docs/getting-started.md
docs/getting-started.ts
src/__integrationtests__/Attestation.spec.ts
src/__integrationtests__/AttestationPE.spec.ts
src/__integrationtests__/Balance.spec.ts
src/__integrationtests__/Ctypes.spec.ts
src/__integrationtests__/Did.spec.ts
src/actor/Attester.spec.ts
src/actor/Claimer.spec.ts
src/actor/Claimer.ts
src/actor/Verifier.spec.ts
src/actor/Verifier.ts
src/credential/Credential.spec.ts
src/crypto/Crypto.spec.ts
src/identity/AttesterIdentity.spec.ts
src/identity/AttesterIdentity.ts
src/identity/Identity.spec.ts
src/identity/Identity.ts
src/messaging/Message.spec.ts
src/messaging/Message.ts
src/requestforattestation/RequestForAttestation.spec.ts

This PR makes portablgabi opt-in and renames `SUBMIT_CLAIMS_FOR_CTYPES_PUBLIC` to `SUBMIT_CLAIMS_FOR_CTYPES_CLASSIC`
- Tests should run succesfully

feat: gabi opt-in, rename public to classic & require mnemonic

---

.prettierignore
package.json
src/claim/Claim.utils.ts
src/crypto/Crypto.ts
src/ctype/CType.utils.ts
src/requestforattestation/RequestForAttestation.utils.ts
src/util/jsonabc.d.ts
src/util/jsonabc.js
yarn.lock

Since we always have problems with the `jsonabc` library in react-native, I copied it directly into the project.
The problems stemmed from the library using a `browser` field in their `package.json`, but not building the library, so it leads to nothing.
In the past we built the file in our react-native projects, which is already not a good solution. To save this hassle, I just copied it here.
- tests should run

feat: copy jsonabc into project

---

src/blockchain/Blockchain.ts
src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
src/identity/Identity.ts

Gets the account nonce via `api.rpc.system.accountNextIndex(accountAddress)` instead as part of `api.query.system.account(accountAddress)`. Using this recently added rpc module will ensure that transactions in the transaction pool will be taken into account when computing the next nonce.
Unfortunately firing two transactions with very little time in between will still result in an error if the first transaction has not yet been added to the transaction pool.
This snippet, pasted into two separate files, will now pass even if both tests are run simultaneously: 
```js
import { Identity, Balance } from './index'
import BN from 'bn.js'
it('makes a transaction', async () => {
const alice = await Identity.buildFromURI('//Alice')
const bob = await …
```

use next nonce rpc

---

src/__integrationtests__/Attestation.spec.ts
src/attestation/Attestation.spec.ts
src/attestation/Attestation.ts
src/attestedclaim/AttestedClaim.ts

method return false, when it was revoked, which seems to be counterintuitive, when the function is just called verify
N/A

Refactor: Change Attestation of verify 

---

src/__integrationtests__/utils.ts
src/balance/Balance.chain.ts
src/balance/Balance.spec.ts
src/balance/Balance.utils.spec.ts
src/balance/Balance.utils.ts
src/balance/index.ts
src/index.ts

Adds `Balance.utils.ts` to the sdk to handle unit denomination and conversion in a central place instead of our separate components.
Create local instance, start demo client and services, add faucet and transfer funds to test if the portrayal of units is correct.

Unit denomination and conversion

---

src/claim/Claim.spec.ts
src/claim/Claim.utils.ts

Fixes Claim errorCheck function to allow falsy values in Claim contents like `0`, `false`, `''`.
Improves readability as well.
create Claim containing the above values.

fix claim error check

---

docs/example.ts
package.json
src/__integrationtests__/Attestation.spec.ts
src/__integrationtests__/AttestationPE.spec.ts
src/__integrationtests__/Balance.spec.ts
src/__integrationtests__/Ctypes.spec.ts
src/__integrationtests__/Delegation.spec.ts
src/__integrationtests__/ErrorHandler.spec.ts
src/actor/Attester.ts
src/balance/Balance.spec.ts
src/blockchain/Blockchain.spec.ts
src/blockchain/Blockchain.ts
src/blockchain/index.ts
src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
src/ctype/CType.spec.ts
src/delegation/DelegationNode.spec.ts
src/delegation/DelegationRootNode.spec.ts
src/did/Did.spec.ts
src/errorhandling/SDKErrors.ts
src/identity/AttesterIdentity.ts
src/identity/Identity.ts
src/util/SubscriptionPromise.spec.ts
src/util/SubscriptionPromise.ts

This PR adds support for doing multiple transactions per account at once, by managing a account specific nonce map and re-signing and re-sending tx that failed with an recoverable error.
Added or Refactored:
- `IS_RELEVANT_ERROR`: regexp based `ErrorEvaluator` that matches recoverable errors.
- `parseSubscriptionOptions`: `SubscriptionPromiseOptions` can be completely or partially omitted when calling any of the Blockchain methods.
- `submitSignedTx`: exported function tries to send tx, catches errors, and rejects either with the original rejection reason, or rejects with ERROR_TRANSACTION_RECOVERABLE if the error can be recovered when re-signing.
- `submitSignedTx`: Blockchain class method, calls exported function submitSignedTx, catches recoverable errors and re-signs and re-sends the …

feat: multiple transactions per account

---

.github/workflows/devpackpublish.yml
.github/workflows/tests.yml
package.json

Since the user with the github token can't push to restricted branches, we have to use one with more rights.

ci: use PAT for pushing prereleases

---

docs/example.ts
src/__integrationtests__/Attestation.spec.ts
src/__integrationtests__/AttestationPE.spec.ts
src/__integrationtests__/Balance.spec.ts
src/__integrationtests__/Ctypes.spec.ts
src/__integrationtests__/Delegation.spec.ts
src/__integrationtests__/ErrorHandler.spec.ts
src/actor/Attester.ts
src/balance/Balance.spec.ts
src/blockchain/Blockchain.spec.ts
src/blockchain/Blockchain.ts
src/blockchain/Blockchain.utils.ts
src/blockchain/index.ts
src/ctype/CType.spec.ts
src/delegation/DelegationNode.spec.ts
src/delegation/DelegationRootNode.spec.ts
src/did/Did.spec.ts
src/identity/AttesterIdentity.ts
src/index.ts

This PR exports Blockchain functions via new namespace `BlockchainUtils`
- Tests should succeed

feat: export Blockchain utils

---

packages/core/src/blockchain/Blockchain.utils.ts

@rflechtner pinpointed an issue with our double spread logic to apply defaults, it might assign properties that are set to undefined.

fix: undefined assignment on double spread

---

.github/workflows/devpackpublish.yml

I noticed our prereleases on npm may differ in version number. That's no biggie, but we could force them to be equal within a prerelease with this proposed change. This way there is no confusion which prereleased subpackage goes with which other.
You can try running the commands I added locally. Use bash.

ci: force all prerelease packages to have the same version

---

packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Ctypes.spec.ts
packages/core/src/__integrationtests__/ErrorHandler.spec.ts
packages/core/src/blockchain/Blockchain.utils.ts
packages/core/src/errorhandling/ExtrinsicError.ts

This PR refactors changes from https://github.com/KILTprotocol/sdk-js/pull/335, to 
- not rely on the order of the keys to map the pallet code to the ExtrinsicError
- not initiate an Error object per ExtrinsicError

refactor: optimised structure for ExtrinsicErrors

---

packages/core/src/did/index.ts
packages/core/src/index.ts
packages/utils/package.json

Type IDidDocumentSigned was used within the Demo-client but wasn't accessible as not exported.
Added a version fix to the utils folder not being updated.
n/a

fix: add missing did type

---

packages/core/src/blockchainApiConnection/BlockchainApiConnection.ts
packages/core/src/blockchainApiConnection/__mocks__/BlockchainQuery.ts
packages/core/src/did/Did.chain.ts
packages/core/src/did/Did.spec.ts
packages/core/src/did/Did.ts
packages/core/src/did/Did.utils.ts

Applies changes to DID type on the mashnet-node proposed in https://github.com/KILTprotocol/mashnet-node/pull/118 as a result of mashnet-node CI failure due to clippy.
```
docker pull kiltprotocol/mashnet-node:develop
docker run -p 9944:9944 kiltprotocol/mashnet-node:develop --dev --ws-port 9944 --ws-external --rpc-external
yarn test:integration
```

refactor: on-chain DID type

---

packages/sdk-js/package.json
packages/sdk-js/src/index.ts
yarn.lock

This PR re-exports the utils package in the sdk-js package
- Import the sdk-js package
- try to access a util function

feat: export utils in sdk-js

---

.github/workflows/npmpublish.yml

This PR fixes the npm publish ci workflow for full releases
Hard to test without doing the actual release.
Compare to the working devpack publish

chore: prepare full npm publish

---

packages/sdk-js/README.md

Some links are hard coded to point to the master or develop branch. This can be very confusing.
Looks like GitHub can resolve paths in the local repository. Removing the domain and branch info prevents jumps between develop and master branch.
We might need to check how this works, when the README is displayed in the API doc or on NPM.
* ho to the start page
* select this branch
* click on links to other documentation

docs: Dev vs Master mixups

---

packages/core/src/balance/Balance.chain.ts

The current example for `listenToBalanceChanges` doesn’t take into account that the method is `async` and returns a promise. I’ve just added an `await`.

fix listenToBalanceChanges example

---

packages/core/src/balance/Balance.utils.spec.ts
packages/core/src/balance/Balance.utils.ts
packages/core/src/balance/index.ts

To make it easier for App developers to work with Balances, we should make our formatKiltBalance more flexible.
Additionally, format it for specific decimal places
Added new test to balance utils

feat: flexible balance formatting

---

docs/example.ts
packages/core/src/__integrationtests__/Balance.spec.ts
packages/core/src/balance/Balance.chain.ts
packages/core/src/balance/Balance.spec.ts
packages/core/src/balance/Balance.utils.spec.ts
packages/core/src/balance/Balance.utils.ts
packages/core/src/balance/index.ts
packages/types/src/Balance.ts
packages/types/src/index.ts

Adding locked, reserved and free balances. 
Unable to add bonded, staked and vesting as pallets are not implemented. 
Run yarn test && yarn test:integration

feat: adding balance locked, reserved and free

---

packages/messaging/src/Message.spec.ts
packages/messaging/src/Message.ts
packages/types/src/Message.ts

Changes the property key of the encrypted message body from `message` to `ciphertext` for clarity.
https://en.wikipedia.org/wiki/Ciphertext

refactor: encrypted message body naming

---

.github/workflows/tests.yml

This PR runs integration tests / getting-started and example against the mashnet-staging network as well as the devnet
- Tests should run
- Devnet tests may fail

ci: tests on mashnet-staging

---

packages/chain-helpers/package.json
packages/core/package.json
packages/types/package.json
yarn.lock

Downgraded to version 4.11.9 to match polkadots current implementation of BN.
No changes to SDK
When updating the polkadot-js version we should take care of matching the appropriate bn.js version.
Run through all the tests

fix: different versions of BN from Polkadot causes issues

---

docs/example.ts
docs/getting-started.md
docs/getting-started.ts
packages/actors_api/src/actors/Attester.ts
packages/chain-helpers/src/blockchain/Blockchain.ts
packages/chain-helpers/src/blockchain/Blockchain.utils.ts
packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Balance.spec.ts
packages/core/src/__integrationtests__/Blockchain.spec.ts
packages/core/src/__integrationtests__/Ctypes.spec.ts
packages/core/src/__integrationtests__/Delegation.spec.ts
packages/core/src/__integrationtests__/ErrorHandler.spec.ts
packages/core/src/balance/Balance.spec.ts
packages/core/src/ctype/CType.spec.ts
packages/core/src/delegation/DelegationRootNode.spec.ts
packages/core/src/did/Did.spec.ts
packages/sdk-js/src/index.ts

Moves `signAndSubmitTx` as exported function to `BlockchainUtils`
added additional instruction for step by step signing and submitting in getting started guide
removed `SubscriptionPromise` from direct sdk-js package export, this is accessible in `ChainHelpers`

feat: move signandsubmit

---

docs/example.ts
docs/getting-started.md
docs/getting-started.ts
packages/actors_api/src/actors/Attester.ts
packages/chain-helpers/src/blockchain/Blockchain.ts
packages/chain-helpers/src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Delegation.spec.ts
packages/core/src/attestation/Attestation.ts
packages/core/src/balance/Balance.chain.ts
packages/core/src/balance/Balance.spec.ts
packages/core/src/ctype/CType.ts
packages/core/src/delegation/Delegation.ts
packages/core/src/delegation/DelegationNode.chain.ts
packages/core/src/delegation/DelegationNode.ts
packages/core/src/delegation/DelegationRootNode.chain.ts
packages/core/src/delegation/DelegationRootNode.ts
packages/core/src/did/Did.ts
packages/core/src/identity/Identity.ts

Updated Docs and functions to account for removed parameter.
`Delegation.revoke` now takes only the necessary address.
More consistent tx workflow documentation and guidance.

fix: outdated docs, unrequired identity

---

packages/messaging/src/Message.ts

This PR renames `message` to `ciphertext` also in the normal Message object
- Tests should run through

refactor: rename message to ciphertext also in normal Message

---

docs/example.ts
docs/getting-started.md
docs/getting-started.ts
packages/chain-helpers/src/blockchain/Blockchain.ts
packages/chain-helpers/src/blockchain/Blockchain.utils.ts
packages/core/src/delegation/Delegation.ts
packages/core/src/identity/Identity.ts
packages/types/src/Blockchain.ts
packages/types/src/Identity.ts

Adds the ability to provide AnyNumber as tip for the validator when signing the tx.
Apart from tip, Polkadot-JS can take multiple different SignerOptions:
```
export interface SignerOptions {
blockHash: Uint8Array | string;
era?: IExtrinsicEra | number;
nonce: AnyNumber | Codec;
signer?: Signer;
tip?: AnyNumber;
}
```
Besides the implemented optional passable options, are any other possible options of interest for us?
- [ x] I have verified that the code works

feat: optional tip for signing tx

---

.gitignore
package.json
packages/actors_api/package.json
packages/chain-helpers/package.json
packages/config/package.json
packages/core/package.json
packages/messaging/package.json
packages/sdk-js/package.json
packages/types/package.json
packages/utils/package.json
packages/vc-export/package.json

Adds `.yarn/versions/` dir to `.gitignore`
bumps version for devpublish to succeed

chore: bump version, fix devpublish

---

.gitignore
package.json
packages/core/src/balance/Balance.chain.ts

Updating the previous recorded balance got removed accidentally in the last balances type refactoring.
Now updates `previousBalance`

fix: update previous balance

---

.eslintignore
.github/workflows/devpackpublish.yml
.github/workflows/npmpublish.yml
.gitignore
.prettierignore
docs/development-setup.md
package.json
packages/sdk-js/README.md
packages/sdk-js/package.json
packages/sdk-js/webpack.config.js
packages/types/src/Identity.ts
yarn.lock

Adds webpack configuration that builds sdk-js bundle in the packages /dist folder as minimized and non-minimized.
Publish with dist folder.
Add to html as script `  <script src="sdk-js.umd.js"></script>`
and use it via `window.sdk`
the script entry name is sdk for now, so to use the script call via window.sdk .
use @kiltprotocol/sdk-js and it's exposed functionalities.

feat: bundle sdk-js and publish in /dist

---

packages/sdk-js/README.md

use @dev tag for bundle access in readme

fix: bundle url

---

packages/chain-helpers/package.json
packages/chain-helpers/src/blockchain/Blockchain.spec.ts
packages/chain-helpers/src/blockchainApiConnection/BlockchainApiConnection.ts
packages/chain-helpers/src/blockchainApiConnection/TypeRegistry.ts
packages/chain-helpers/src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts
packages/chain-helpers/src/blockchainApiConnection/__mocks__/BlockchainQuery.ts
packages/chain-helpers/src/blockchainApiConnection/index.ts
packages/chain-helpers/src/index.ts
packages/core/src/balance/Balance.spec.ts
packages/core/src/did/Did.spec.ts
packages/core/src/identity/PublicIdentity.spec.ts
yarn.lock

Imports the types repo in the sdk so we don't have to copy-paste type definitions and maintain them in two different places.
Also exports the types registry used by the API which allows you to create SCALE (chain) types without connecting to the blockchain.
Currently does not provide a mechanism to choose with which types you want to use the sdk (wasn't possible before, not sure we need it). This means that the sdk would likely only ever work with the latest chain version. 
Run against latest develop chain. Will still fail most likely because integration is not fixed, but this shouldn't fail due to types issues.

feat: use types repo

---

docs/example.ts
docs/getting-started.md
docs/getting-started.ts
packages/actors_api/src/actors/Attester.spec.ts
packages/actors_api/src/actors/Attester.ts
packages/actors_api/src/actors/Claimer.spec.ts
packages/actors_api/src/actors/Claimer.ts
packages/actors_api/src/actors/Verifier.ts
packages/messaging/src/Message.spec.ts
packages/messaging/src/Message.ts

Separate message objects
Message constructor creates a message object. Removed encryption and changed sender from `Identity` to `IPublicIdentity`
Encrypt and decrypt are methods for the message object. Takes sender `Identity` and receiver `PublicIdentity`
`yarn test`

refactor: Removing encryption from message constructor

---

packages/messaging/src/Message.utils.spec.ts
packages/messaging/src/Message.utils.ts
packages/types/src/Terms.ts

Added an optional array `ICType` to `ITerms` interface.
- Step 1
- Step 2
- etc.

feat: CTypes to iterms

---

packages/chain-helpers/src/blockchainApiConnection/BlockchainApiConnection.ts

fix for the disconnect due to old WebSocket instances

fix: disconnect fix

---

.eslintrc.js
LICENSE
packages/did/README.md

The LICENSE file still had `Copyright 2019`, while the rest of the code uses `2018-2021`

chore: change years in LICENSE

---

packages/chain-helpers/src/blockchain/SubscriptionPromise.ts
packages/chain-helpers/src/errorhandling/ExtrinsicError.ts
packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Delegation.spec.ts
packages/core/src/__integrationtests__/Did.spec.ts
packages/core/src/attestation/Attestation.chain.ts
packages/core/src/attestation/Attestation.ts
packages/core/src/delegation/DelegationNode.chain.ts
packages/core/src/delegation/DelegationNode.ts
packages/did/src/Did.chain.ts

This PR adds:
- support to query the amount of KILTs needed to deposit before creating an attestation, a delegation, or a DID
- support to query all the deleted DID identifiers and also to check whether a given DID identifier has been deleted (or blacklisted).
For both features, integration tests have been added.
- Node commit with which this PR has been tested to work: https://github.com/KILTprotocol/mashnet-node/commit/2e937de64c2c0979d2f1b74b8faa2a038707828c
- Fixes https://github.com/KILTprotocol/ticket/issues/1657
- Fixes https://github.com/KILTprotocol/ticket/issues/1639
Blocking https://github.com/KILTprotocol/sdk-js/pull/431.

feat: add querying support for deposits and deleted DIDs

---

docs/example.ts

In the last merge, the ctypehash in example.ts was not correctly extracted. This fixed it.

docs: extract ctypeHash in example.ts

---

packages/did/package.json
packages/did/src/DidDetails/LightDidDetails.spec.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts
packages/did/src/global.d.ts
yarn.lock

This updates the CBOR dependency to the latest version, because v6 doesn't work in the Sporran extension.
Since it uses the global URL object and it is missing from the type-definitions (I opened a discussion here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57055), I had to add a typescript declaration file for it.
- Run tests
- Test in sporran

chore: update cbor to v8

---

docs/example.ts
packages/core/src/__integrationtests__/Deposit.spec.ts
packages/core/src/__integrationtests__/utils.ts

Import Keyring and types from self exposed location, to avoid having redundant packages, reducing bundle size etc.
This could also be done with all the other polkadot stuff we use.

fix: keyring and type from self exposed

---

packages/core/src/__integrationtests__/Delegation.spec.ts
packages/core/src/delegation/DelegationNode.chain.ts
packages/core/src/delegation/DelegationNode.spec.ts
packages/core/src/delegation/DelegationNode.ts

This PR fixes https://github.com/KILTprotocol/ticket/issues/1685 by adding a new function on `DelegationNode` and the relative chain file to generate a `SubmittableExtrinsic` for the `reclaim_deposit` chain function.
This PR targets `develop` commit https://github.com/KILTprotocol/mashnet-node/commit/fc56483437001e68174f47b424fc0c6b01ad35be and `master` commit https://github.com/KILTprotocol/mashnet-node/commit/dff5ae8646753484cf594cd9af1184bd93bd405e (integration tests for this branch are failing as delegation deposits have not yet been merged).
Companion PR (already merged on `develop`) -> https://github.com/KILTprotocol/mashnet-node/pull/295

feat: add support for delegation deposit reclaim

---

packages/did/src/DidDetails/LightDidDetails.spec.ts
packages/did/src/DidDetails/LightDidDetails.utils.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts

references https://github.com/KILTprotocol/sdk-js/pull/448. Look there for a problem description.
Instead of supporting both `base64` and `base58`. This PR switches completely to `base58`.
It also add the "multibase" flag for base58 and a custom flag `0` for our current serialisation algorithm (which is a custom object fed into cbor)

fix: light did encoding

---

packages/chain-helpers/package.json
packages/config/package.json
packages/core/package.json
packages/did/package.json
packages/messaging/package.json
packages/sdk-js/package.json
packages/types/package.json
packages/utils/package.json
packages/vc-export/package.json

This PR adds declaration files to the `lib/esm` folder, in case someone imports a file per direct path import. (Otherwise they wouldn't be able to access the types)
- Use in a project and import a file like this:
```
import { validateAddress } from '@kiltprotocol/utils/lib/esm/DataUtils'
```
- Try to jump to definition in IDE, or transpile with TS

chore: export type declarations for esm

---

packages/core/src/__integrationtests__/Delegation.spec.ts
packages/did/src/Did.utils.ts
packages/messaging/src/Message.spec.ts
packages/messaging/src/Message.ts

Fixes a bug in the message verification logic which used to match for equality between sender and owner.
This PR introduces an utility function in `DidUtils` called `isSameSubject(didA, didB)` which returns `true` if both DIDs refer to the same subject (i.e., the two DIDs share the same identifier). Several unit tests have been added to the messaging unit tests.

fix: ensure message is owner in messages

---

packages/sdk-js/README.md

The current SDK readme shows outdated links for workshop and careers page. This PR fixes that.

docs: fix links in SDK README

---

packages/utils/src/Crypto.ts

This PR fixes an import problem, when using in a create-react-app project.
- use yalc to publish `@kiltprotocol/utils`
- use it via esm
- use it via cjs

fix: jsonabc import

---

packages/chain-helpers/src/blockchain/Blockchain.utils.ts
packages/testing/src/mocks/mockedApi.ts

To avoid tx status & event subscription to go stale or miss important updates (like finalisation), this makes sure that they are rejected on disconnect. Users would then have to go and check on chain if their transactions were successful by checking the desired effects. 
Using a test chain, make a transaction, submit it via the Blockchain helpers and interrupt the connection after receiving the `isReady` status update (e.g. by switching wifi off).

fix: reject subscription promise on disconnect

---

.github/workflows/tests-polkadot-deps.yml
packages/did/src/global.d.ts
packages/testing/src/mocks/typeRegistry.ts
yarn.lock

Will run unit & integration tests every Saturday night, using an install with no lock file. That means all dependencies are at their latest version allowed by the semver range.
Will run from the default branch (develop), but will checkout master (latest commit).
I fixed two type issues in an attempt to make the tests run on the current branch with the latest polkadot deps, but could revert that potentially. 
I'm torn especially about deleting the `global.d.ts` (https://github.com/KILTprotocol/sdk-js/pull/481/commits/06c536bc504aeee883ebc08522875a54c1881037) although it constituted a dirty fix for a specific version of `@types/node` that is lacking some global definitions. The community was torn on this one and removed and re-added it repeatedly, so that some versions have it, others …

test against updated dependencies

---

packages/did/src/Did.chain.ts
packages/did/src/DidDetails/LightDidDetails.spec.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts
packages/types/src/DidDetails.ts

Revert the encoding of all key types to be lowercase, e.g. `X25519` -> `x25519` for retro-compatibility with lightDID encoding logic.

fix: update key types encoding for retro-compatibility

---

packages/did/src/global.d.ts
yarn.lock

Bumps `@types/node` in our lock file to a version that includes global definitions for `URL` and removes these definitions from our repo. This is to avoid conflicts between declarations as typescript does not simply merge these. 
SDK consumers for whom this creates issues should either update their node types, make a global declaration in their own project or disable dependency type checks. 
N/A

fix: bump node types

---

packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Delegation.spec.ts
packages/core/src/__integrationtests__/Did.spec.ts

fixes https://github.com/KILTprotocol/sdk-js/issues/504
As far as I can see the only issue leading to failure in our weekly run with updated deps is that the integration tests are out of sync with the latest chain runtime. This should take care of the problem.

hotfix: cherry pick integration test fix for scheduled runs

---

packages/did/src/DidDetails/FullDidDetails.utils.ts

The DID logic did not include any DID key for the `didLookup` pallet, which accepts a DID origin with an authentication key.
Use `"@kiltprotocol/sdk-js": "0.26.1-beta.1"` against a version of the node that has the fixed origin, e.g., https://github.com/KILTprotocol/mashnet-node/pull/343.

fix: add authentication key requirement for didLookup pallet calls

---

.github/workflows/tests-polkadot-deps.yml
packages/testing/src/mocks/metadata/spiritnet.json

Because master currently still has the updateMetadata script set to an unreliable endpoint and we check out master in scheduled tests, this still fails.
By forcing the endpoint from the workflow file (which is executed from develop) this would be fixed.

ci: fix metadata update on scheduled tests

---

packages/core/src/__integrationtests__/AccountLinking.spec.ts
packages/did/src/DidLinks/AccountLinks.chain.ts

BREAKING CHANGE: rename `authorizeLinkWithAccount` to `getAuthorizeLinkWithAccountTx`
One is not like the others!
```
function getAssociateSenderTx(): Promise<Extrinsic>
function getAccountSignedAssociationTx(): Promise<Extrinsic>
function getReclaimDepositTx(): Promise<SubmittableExtrinsic>
function getLinkRemovalByAccountTx(): Promise<SubmittableExtrinsic>
function getLinkRemovalByDidTx(): Promise<Extrinsic>
function authorizeLinkWithAccount(): Promise<Extrinsic>
```
All function that return an extrinsic are called `get...Tx` except this one, which is confusing. I expected that this does something else. 😅

refactor: consistent naming

---

packages/core/src/requestforattestation/RequestForAttestation.spec.ts
packages/core/src/requestforattestation/RequestForAttestation.utils.ts

Don't throw an error in verify method.

refactor: no throw in verify

---

.github/renovate.json

This adds a renovate config to the repo. Repo maintainers would have to add the [renovate app](https://github.com/marketplace/renovate) to the repo for this to have an effect.
I set this up on a fork so I can test it. Look at the PRs it has created, works quite nicely.

feat: add renovate config

---

docs/contribution-guide.md
packages/core/src/attestation/Attestation.ts
packages/core/src/balance/Balance.chain.ts
packages/core/src/credential/Credential.ts
packages/core/src/delegation/DelegationNode.ts
packages/core/src/requestforattestation/RequestForAttestation.ts
packages/did/src/DidDetails/LightDidDetails.utils.ts

This removes all @example entries from the jsdoc comments.
- Open code editor
- Search for "@example"
- find nothing

chore: remove all @example jsdocs

---

tsconfig.json

This PR changes the development tsconfig to only include relevant folders to prevent over-reporting of `yarn check`
- Run `yarn check`

chore(tsconfig): only include packages of interest

---

package.json

When updating the yarn version, one mention of the old version was omitted

packageManager: yarn@3.0.2

---

packages/core/src/__integrationtests__/utils.ts
packages/core/src/attestation/Attestation.chain.ts
packages/core/src/delegation/DelegationNode.chain.ts
packages/utils/src/SDKErrors.ts
tests/bundle.spec.ts

Because the current spiritnet does not have the new delegation / authorisation logic on the Attestation pallet deployed, with this PR the sdk handles both old and new.
Integration tests now work for latest-develop and latest tags (with the exception of a snapshot test).

feat: attestation module flexibly handles old delegation pallet

---

packages/core/src/__integrationtests__/Attestation.spec.ts

Makes the deposit amount test accept the old and the new value while we’re in transition
yarn run test:integration packages/core/src/__integrationtests__/Attestation.spec.ts

fix: deposit amount test

---

.github/workflows/semantic-pull-request.yml

When squashing commits to merge the PR, the PR title becomes the commit message. We want our commits to be formatted as conventional/semantic commits, and this requirement propagates to the PR titles. This action should validate the PR title to follow the conventional commits guidelines.
Change the title of the PR to not match the conventional commits guidelines and see this action fail. This will not work on the current PR because of [specific configuration](https://github.com/amannn/action-semantic-pull-request#event-triggers), but failures and successes can be seen in the [action history](https://github.com/KILTprotocol/sdk-js/actions/workflows/semantic-pull-request.yml).

feat: conventional/semantic PR titles

---

packages/core/src/credential/Credential.spec.ts
packages/core/src/ctype/CType.spec.ts

jest.mocked() is a type-aware alternative to `value as jest.Mock`
Try passing a value of incorrect type to `mockResolvedValue()`

feat: use jest.mocked()

---

packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Balance.spec.ts
packages/core/src/__integrationtests__/Did.spec.ts
packages/core/src/balance/Balance.spec.ts
packages/core/src/claim/Claim.spec.ts
packages/core/src/delegation/DelegationNode.spec.ts
packages/core/src/delegation/DelegationNode.ts
packages/did/src/Did.chain.ts
packages/did/src/Did.utils.ts
packages/did/src/DidBatcher/FullDidCreationBuilder.ts
packages/did/src/DidDetails/DidDetails.ts
packages/did/src/DidDetails/FullDidDetails.spec.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.ts
packages/did/src/DidResolver/Resolver.spec.ts
packages/messaging/src/Message.spec.ts
packages/messaging/src/Message.utils.spec.ts
packages/messaging/src/Message.utils.ts
packages/testing/src/mocks/mockedApi.ts
packages/utils/src/Crypto.spec.ts

The shorthand form of the arrow functions is more declarative and should be used where possible
yarn test

feat: use arrow functions shorthand

---

packages/chain-helpers/src/blockchain/SubscriptionPromise.spec.ts
packages/core/src/__integrationtests__/AccountLinking.spec.ts
packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Balance.spec.ts
packages/core/src/__integrationtests__/Blockchain.spec.ts
packages/core/src/__integrationtests__/Ctypes.spec.ts
packages/core/src/__integrationtests__/Delegation.spec.ts
packages/core/src/__integrationtests__/Deposit.spec.ts
packages/core/src/__integrationtests__/Did.spec.ts
packages/core/src/__integrationtests__/ErrorHandler.spec.ts
packages/core/src/__integrationtests__/Web3Names.spec.ts
packages/core/src/credential/Credential.spec.ts
packages/core/src/ctype/CType.spec.ts
packages/core/src/delegation/DelegationNode.spec.ts
packages/core/src/quote/Quote.spec.ts
packages/core/src/requestforattestation/RequestForAttestation.ts
packages/did/src/Did.chain.spec.ts
packages/did/src/Did.signature.spec.ts
packages/did/src/DidResolver/DidResolver.ts
packages/did/src/DidResolver/Resolver.spec.ts
packages/testing/scripts/fetchMetadata.js
packages/vc-export/src/exportToVerifiableCredential.spec.ts
packages/vc-export/src/vc-js/suites/KiltAttestedSuite.spec.ts
packages/vc-export/src/vc-js/suites/KiltIntegritySuite.spec.ts
packages/vc-export/src/vc-js/suites/KiltSignatureSuite.spec.ts

The expect() checks of async functions in the tests can be simplified
yarn test

feat: remove unnecessary use of .resolves

---

packages/core/src/attestation/Attestation.ts
packages/core/src/claim/Claim.ts
packages/core/src/credential/Credential.spec.ts
packages/core/src/ctype/CType.chain.ts
packages/core/src/delegation/DelegationNode.ts
packages/core/src/delegation/DelegationNode.utils.ts
packages/core/src/quote/Quote.ts
packages/core/src/requestforattestation/RequestForAttestation.ts
packages/did/src/Did.utils.ts
packages/did/src/DidBatcher/FullDidUpdateBuilder.ts
packages/did/src/DidDetails/DidDetails.ts
packages/did/src/DidDetails/FullDidDetails.ts
packages/did/src/DidDetails/LightDidDetails.ts
packages/did/src/DidLinks/Web3Names.chain.ts
packages/did/src/DidResolver/DidResolver.ts
packages/did/src/DidResolver/Resolver.spec.ts
packages/did/src/types.ts
packages/messaging/src/Message.spec.ts
packages/messaging/src/Message.ts
packages/messaging/src/Message.utils.spec.ts
packages/types/src/Attestation.ts
packages/types/src/CType.ts
packages/types/src/Claim.ts
packages/types/src/Delegation.ts
packages/types/src/DidDetails.ts
packages/types/src/DidDocumentExporter.ts
packages/types/src/DidResolver.ts
packages/types/src/Message.ts
packages/types/src/Quote.ts
packages/vc-export/src/vc-js/suites/KiltSignatureSuite.spec.ts

The DID is a foundational feature of the KILT protocol, so I think it’s fair to treat the types `DidUri` and `DidResourceUri` as foundational types that can be used directly in most places, excluding maybe those where indirection provides helpful hints.

feat: use DID types directly

---

packages/core/src/__integrationtests__/Did.spec.ts
packages/did/src/Did.chain.spec.ts
packages/did/src/Did.chain.ts
packages/did/src/Did.utils.ts
packages/did/src/DidBatcher/FullDidBuilder.spec.ts
packages/did/src/DidBatcher/FullDidBuilder.ts
packages/did/src/DidBatcher/FullDidCreationBuilder.spec.ts
packages/did/src/DidBatcher/FullDidUpdateBuilder.spec.ts
packages/did/src/DidDetails/FullDidDetails.spec.ts
packages/did/src/DidDetails/LightDidDetails.spec.ts
packages/did/src/DidDetails/LightDidDetails.utils.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.ts
packages/did/src/DidResolver/DidResolver.ts
packages/did/src/DidResolver/Resolver.spec.ts
packages/messaging/src/Message.spec.ts
packages/types/src/DidDetails.ts
packages/types/src/DidDocumentExporter.ts

DID service endpoint URIs are not URLs.
yarn test

fix!: rename service endpoint URLs to URIs

---

packages/core/src/credential/Credential.ts

This PR adds clarity to the Credential.verify checks and always checks signature, if it is present.

feat: clarity in Credential.verify

---

packages/core/src/__integrationtests__/Deposit.spec.ts
packages/core/src/__integrationtests__/Web3Names.spec.ts
tests/bundle-test.ts

We already have reasonable defaults for when to resolve the submit transaction promise. I removed the boilerplate-y over-specification of those.

feat: use finalization defaults

---

packages/core/src/credential/Credential.ts
packages/core/src/delegation/DelegationNode.ts
packages/core/src/quote/Quote.ts
packages/did/src/Did.utils.ts
packages/did/src/DidDetails/FullDidDetails.ts
packages/types/src/DidDetails.ts

Looks like we only ever choose from one key, let’s remove the keySelection for now to avoid confusion.

feat!: drop keySelection

---

packages/messaging/src/Message.spec.ts
packages/messaging/src/Message.ts

This PR separates message decryption and content verification.
Breaking change, because people might have relied on message.decrypt to do message verification
- Tests need to run through

feat(message)!: separate verify function

---

packages/augment-api/package.json
packages/augment-api/scripts/fixTypes.mjs
packages/augment-api/src/interfaces/extraDefs/index.ts
packages/augment-api/src/interfaces/index.ts
packages/augment-api/src/interfaces/types.ts
yarn.lock

For es module imports every import needs a file extension, which we generally check with an eslint rule.
We don't for autogenerated files in the augment-api package, however, because these are marked with eslint-disable.
This has resulted in import issues.
This fix runs a regex-based search-replace to fix any affected import in the directory where autogenerated files are placed.
All imports should now have an extension.

fix: augmentation hacks

---

.github/workflows/tests.yml

This PR introduces tests against node v18.
It also fixes the CI actions, to actually test with the node versions 14, 16 and 18. Before, only the build step would build a package per node versions, but would test all of them with the same node version.
- Tests need to run

chore: upgrade CI to use node v18

---

.eslintrc.js

This PR changes the eslint tsconfig option to use the one used by the IDE.
- Try to generate a problem for strict-boolean-checks

style: use the base tsconfig for eslint type info

---

packages/config/src/ConfigService.ts
packages/core/src/attestation/Attestation.ts
packages/core/src/claim/Claim.spec.ts
packages/core/src/claim/Claim.ts
packages/core/src/credential/Credential.ts
packages/core/src/ctype/CType.ts
packages/did/src/Did.signature.spec.ts
packages/did/src/Did.signature.ts
packages/did/src/Did.utils.ts
packages/messaging/src/Message.ts
packages/utils/src/SDKErrors.ts

Refactors functions that were typed as type guards such that they do not throw, but always return a boolean.
This is the expected behaviour of a type guard.
Also enforces a naming convention where type guards must begin with `is...`.
Also removed 2 errors that have become or were already obsolete (unused in the sdk).
Tests are included.

chore!: type guards should not throw

---

packages/chain-helpers/src/blockchain/Blockchain.spec.ts
packages/chain-helpers/src/blockchain/Blockchain.ts
packages/config/package.json
packages/config/src/ConfigService.ts
packages/core/src/__integrationtests__/Blockchain.spec.ts
packages/core/src/__integrationtests__/utils.ts
packages/testing/src/TestUtils.ts
tests/bundle-test.ts
yarn.lock

Adding a config service option to set a default for the resolveOn parameter on `submitTx`, which will be used whenever this parameter is not set.
Also inlining the `parseSubscriptionOption` function which had little to no purpose at this point
Tests

feat: default tx subscription resolution config

---

packages/core/src/attestation/Attestation.ts
packages/core/src/credential/Credential.ts
packages/core/src/kilt/Kilt.ts

Selective disclosure turned out to be broken in the latest rc.
Additionally to fixing this, the docstring of `Kilt.connect()` was not particularly informative about what it actually does.

fix: selective disclosure

---

packages/core/src/attestation/Attestation.chain.ts
packages/core/src/ctype/CType.chain.ts
packages/core/src/delegation/DelegationDecoder.ts
packages/did/src/Did.chain.ts
packages/did/src/DidLinks/AccountLinks.chain.ts
packages/did/src/DidLinks/Web3Names.chain.ts

This PR replaces the type casting of KILT accounts returned from blockchain with encoding them. Many cases don’t even need that, rather they want to get DidUri from blockchain data using `Did.uriFromChain()`.
Inspired by the [review comment](https://github.com/KILTprotocol/sdk-js/pull/613#discussion_r970700877)

feat: Did.uriFromChain and encode replaces type cast

---

packages/core/src/__integrationtests__/AccountLinking.spec.ts
packages/core/src/__integrationtests__/Did.spec.ts
packages/did/src/DidResolver/DidResolver.spec.ts
packages/did/src/DidResolver/DidResolver.ts
packages/testing/src/mocks/mockedApi.ts

This PR uses a more clear and readable call instead of another one, performance benefits of which have apparently failed to materialize.
Inspired by a [review comment](https://github.com/KILTprotocol/sdk-js/pull/613#discussion_r970741095)

feat: avoid .hash().isEmpty

---

packages/core/src/__integrationtests__/AccountLinking.spec.ts
packages/core/src/__integrationtests__/Did.spec.ts
packages/did/src/Did.chain.spec.ts
packages/did/src/Did.chain.ts
packages/did/src/Did.utils.ts
packages/did/src/DidDetails/FullDidDetails.spec.ts
packages/did/src/DidDetails/FullDidDetails.ts
packages/did/src/DidDetails/LightDidDetails.utils.ts
packages/did/src/DidLinks/AccountLinks.chain.ts
packages/did/src/DidResolver/DidResolver.spec.ts
packages/did/src/DidResolver/DidResolver.ts

This is a follow-up for #613 to remove some more chain wrappers: 
Did.Chain.queryServiceEndpoints
Did.Chain.getAddEndpointExtrinsic
Did.AccountLinks.getAuthorizeLinkWithAccountExtrinsic
We also remove the validations of lengths and amounts for properties of a DID service, as they should be done by application developers on higher level, and are already done by the blockchain itself.
serviceEndpointFromChain renamed to serviceFromChain

refactor!: remove more chain wrappers

---

packages/core/src/index.ts
packages/core/src/kilt/Kilt.ts
packages/sdk-js/package.json
packages/sdk-js/src/index.ts
tests/bundle-test.ts
yarn.lock

Make the ConfigService directly available when importing from the sdk-js.
Removes the redundant `Kilt.config()` function.

feat!: export ConfigService from the SDK

---

packages/testing/src/TestUtils.ts
packages/types/src/Address.ts
packages/utils/src/Crypto.ts
tests/bundle-test.ts

This PR adds a missing type for the encryption keypair: `KiltEncryptionKeypair`

feat: added KiltEncryptionKeypair

---

packages/did/src/Did.utils.ts
packages/did/src/DidDetails/FullDidDetails.spec.ts
packages/did/src/DidDetails/FullDidDetails.ts
packages/utils/src/SDKErrors.ts

This PR addresses a TODO remnant from #581 and renames a legacy error.

chore: rename DidBuilderError

---

packages/core/src/kilt/Kilt.ts
packages/core/src/quote/Quote.ts
packages/did/src/Did.chain.ts
packages/did/src/Did.utils.ts
packages/did/src/DidDetails/FullDidDetails.ts
packages/did/src/DidDetails/LightDidDetails.spec.ts
packages/did/src/DidLinks/AccountLinks.chain.ts
packages/did/src/DidResolver/DidResolver.spec.ts
packages/testing/src/TestUtils.ts
packages/utils/src/Crypto.ts

This PR cleans up some leftovers reported by eslint.

fix: missing JSDoc annotations and other lints

---

packages/augment-api/package.json
packages/core/package.json
yarn.lock

Imports of @kiltprotocol/type-definitions are referencing different version ranges (one is pinned, one is not) leading to duplicate resolutions. This pins both to the latest version.

chore: pin type-definitions to same version

---

.github/workflows/tests-polkadot-deps.yml

Weekly tests have been failing because the script they use to update the chain metadata for tests has been moved.
This PR fixes this.
__We could also think about removing that step altogether though, as checking for incompatibilities with new polkadot package versions should be considered separate from checking for incompatibilities introduced by runtime upgrades.__

fix: metadata update command in weekly tests

---

packages/core/src/__integrationtests__/AccountLinking.spec.ts
packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Balance.spec.ts
packages/core/src/__integrationtests__/Blockchain.spec.ts
packages/core/src/__integrationtests__/Ctypes.spec.ts
packages/core/src/__integrationtests__/Delegation.spec.ts
packages/core/src/__integrationtests__/Deposit.spec.ts
packages/core/src/__integrationtests__/Did.spec.ts
packages/core/src/__integrationtests__/ErrorHandler.spec.ts
packages/core/src/__integrationtests__/Web3Names.spec.ts
packages/core/src/__integrationtests__/utils.ts
packages/did/src/DidDetails/FullDidDetails.spec.ts
packages/did/src/DidDetails/FullDidDetails.ts
packages/testing/src/mocks/mockedApi.ts
tests/bundle-test.ts

Renamed `authorizeExtrinsic()` to `authorizeTx()` and applied the same to all the methods with `Extrinsic` in their names. Inconsistent naming is confusing, and even the word "extrinsic" is not the most tongue-friendly.
authorizeExtrinsic -> authorizeTx
submitExtrinsic -> submitTx
getKeyRelationshipForExtrinsic -> getKeyRelationshipForTx
getKeysForExtrinsic -> getKeysForTx

feat: align from *Extrinsic to *Tx method names

---

.github/workflows/tests.yml

Failing workflows indicate that there may be a problem with checkoutv1. This updates the only use of that GitHub action to v3.

fix: checkout v1 seems broken

---

packages/core/src/credential/Credential.ts
packages/core/src/quote/Quote.spec.ts
packages/core/src/quote/Quote.ts
packages/did/src/Did.signature.spec.ts
packages/did/src/Did.signature.ts
packages/messaging/src/Message.spec.ts
packages/testing/src/TestUtils.ts
packages/utils/src/Crypto.ts

As per the ticket, this changes verifyDidSignature such that it takes signatures as a byte array instead of a hex string.
It also removes the makeDidSignature helper.
Unit tests have been adapted.

refactor!: make verifyDidSignature accept Uint8Array

---

packages/config/package.json
yarn.lock

We have been using a pre-v1 version of typescript-logging. By now v2 is out (which has breaking changes) but there seems to be no reason not to upgrade to v1.

chore: bump typescript-logging to v1

---

packages/core/src/credential/Credential.spec.ts
packages/core/src/credential/Credential.ts
packages/core/src/quote/Quote.ts
packages/did/src/Did.signature.spec.ts
packages/did/src/Did.signature.ts
packages/did/src/DidResolver/DidResolver.ts

Checking whether the signer of a credential is (related to) the owner has is so far not happening as part of `verifyPresentation`.
This adds this feature to `verifyDidSignature`, which is called by `verifyPresentation`.
> __Note:__ This cherry-picks a commit (01bf6fd1a98d5a75a18d90491c97b220ca94bb68) originally included with  https://github.com/KILTprotocol/sdk-js/pull/675.
Unit tests related to that issue did not exist yet. I added these.

feat: compare owner and signer of credential on signature verification

---

packages/core/src/quote/Quote.spec.ts
packages/core/src/quote/Quote.ts
packages/types/src/Quote.ts

- Sign `claimerDid` and credential `rootHash` into quote agreement
- Check that attester signature can be matched to attesterDid and claimer signature to claimerDid
- Make Quote agreement verification easier with new `verifyQuoteAgreement` function. 
> __Note:__ This shares a commit (01bf6fd1a98d5a75a18d90491c97b220ca94bb68) with https://github.com/KILTprotocol/sdk-js/pull/674.
Unit tests included

feat: improve quote verification

---

packages/type-definitions/src/index.ts
packages/type-definitions/src/types_10800.ts
packages/type-definitions/src/types_10900.ts

Ethereum linking has been pushed to the next release 1.9.0, so this PR updates the types accordingly.

chore: update type definitions

---

packages/type-definitions/src/index.ts

* adds Peregrine Staging Chain name to type decorations

fix: add peregrine stg chain to type decorations

---

babel.config.json
jest.config.js
package.json
yarn.lock

Unit- and integration tests would sometimes get stuck in the startup phase for minutes, as they transpile polkadot-js dependencies that unfortunately are not always 100% clean cjs code - somehow esm export statements seem to sneak into the dependency tree, leading to all tests failing.
Using babel to transpile js files instead of tsc (which only transpiles ts now) appears to buy us significant performance gains, with startup times being reduced to 15-20 seconds on my system.
This comes at the cost of a slightly larger development install, as we now need more babel dependencies. 
Build sdk and run tests on your machine, report how that goes.

refactor: reduce startup time of tests by using babel to transpile js

---

packages/did/src/DidResolver/DidResolver.spec.ts
packages/did/src/DidResolver/DidResolver.ts
packages/types/src/DidDocumentExporter.ts
packages/types/src/DidResolver.ts

Adds an implementation of the `resolve` function described by the resolution section of the DID specifications (https://www.w3.org/TR/did-core/#resolution) - rn I called it `compliantResolve`, because `DID.resolve` is taken in the sdk.
Main differences: 
- Returns an actual DID document, i.e. the result of `exportToDidDocument`.
- Returns a minimal DID document if a DID has been deleted or upgraded, instead of returning no document.
- Adds a `resolutionMetadata` structure, which can indicate resolution errors.
- Does not throw/return `null` for invalid/non-existent DIDs, but uses the `resolutionMetadata` error reporting.
To be able to add the `alsoKnownAs` field to the DidDocument, I also changed the signature of `resolve` to include the web3name in the returned data, if available.
Unit …

feat: DID spec compliant implementation of resolve 

---

.eslintrc.js
packages/core/src/__integrationtests__/Ctypes.spec.ts
packages/core/src/ctype/CType.chain.ts

Makes sure the sdk still decodes CType records from before the chain upgrade to 0.9.0 / 0.8.5.
Adjust tests so that CType fetching is skipped where not available.
We should no longer see the `Invalid empty address passed` errors in integration tests against `latest` (e.g., https://github.com/KILTprotocol/sdk-js/actions/runs/4003744234/jobs/6872161008).
~Fetching CType data will still fail with `Cannot fetch CType definitions on a chain that does not store the createdAt block`.~

feat: backwards-compatible ctype data decoding

---

packages/core/src/__integrationtests__/utils.ts
packages/core/src/kilt/Kilt.ts

Allows passing additional arguments for ApiPromise.create in `connect()` via a second parameter.
Furthermore, sets the default value of one of them (`noInitWarn`) based on the current log level.
Calling `connect` should produce more log output concerning types and augmentation if the log level had been set to 3 and below compared to setting it to 4 or 5.

feat: allow passing additional arguments to ApiPromise.create

---

.github/workflows/test-node-candidate.yml

Fixes https://github.com/KILTprotocol/ticket/issues/2405.
It adds a manual dispatch workflow which takes a `tag` parameter representing the tag of the `kiltprotocol/prototype-chain` Docker image to use for integration tests. We can think of more advanced setups in the future, but for now this should work, and make it at least possible to test the SDK with a release candidate without any workarounds.

chore: add workflow for manual dispatch against a Docker node tag

---

packages/did/src/DidDocumentExporter/DidContexts.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.ts
packages/did/src/DidDocumentExporter/index.ts

Adds static copies of json-ld context files relevant to KILT DID documents to the sdk, as well as the respective URI to DID documents exported to the conformant json-ld representation.
n/a

feat: add did contexts

---

packages/core/src/credential/Credential.spec.ts
packages/core/src/ctype/CType.schemas.ts
packages/core/src/ctype/CType.spec.ts
packages/core/src/ctype/CType.ts
packages/core/src/ctype/Ctype.nested.spec.ts
packages/types/src/CType.ts
packages/utils/src/SDKErrors.ts

Introduces a new meta schema to fix the issue that additional properties were not validated.
Newly created CTypes would use this meta schema by default; legacy CTypes are still validated against the old meta schema.
- Unfortunately it seems that the only viable strategy so far is deriving a schema from the CType.
- Better compatibility could be achieved by defining an optional `@id` property on all CTypes (to avoid failing credentialSubjecct verification on VCs, where this would be present after expanding), but this comes at a cost; any IClaim would pass verification even with an extra `@id` property.
-  Because the currently used json schema version does not allow defining a CType which derives the full set of properties from another CType (you can only add references for each property …

fix: current CType meta schema ignores additional properties in claim contents

---

packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Delegation.spec.ts
packages/core/src/attestation/Attestation.ts
packages/core/src/credential/Credential.spec.ts
packages/core/src/credential/Credential.ts
packages/core/src/delegation/DelegationNode.ts

This changes the function signature of `verifyCredential` and `verifyPresentation` so that all verification steps are covered, including querying the attestation. They now return the credential enriched with attester and revocation info. Assertions about both are __NOT__ made, but these depend a lot on your application logic and are trivial to do with the data returned from these functions.
I like the idea of having a data model for a `VerifiedCredential` bc it allows introducing another function, called `refreshRevocationStatus` here, which queries the attestation again and throws not only failing if the attestation has been deleted or has been recreated with incoherent data, but also if it has been recreated by a different attester. This avoids potential exploits where a verifier who …

refactor!: fetch attestation as part of verifyCredential

---

packages/core/src/balance/Balance.utils.ts

In the most recent version(s), Polkadot-js has started to do an odd locale-based formatting of balances where only the separators change but the numerals remain unchanged. This broke our formatting for locales using different numerals.
- delete yarn.lock and run `yarn install`
- run tests

fix: fromFemtoKilt fails for non-english locales

---

packages/did/src/DidLinks/AccountLinks.chain.ts

This makes it possible to use the high level `associateAccountToChainArgs` in most cases, but also use the building blocks in edge cases where parts are already done by other parts of the app (e.g. the wrapping of bytes).

feat: split `associateAccountToChainArgs`

---

packages/core/src/ctype/CType.schemas.ts
packages/core/src/ctype/CType.spec.ts
packages/core/src/ctype/Ctype.nested.spec.ts
packages/types/src/CType.ts
packages/types/src/Claim.ts

Amends the new CType metaschema with new features:
- Allowable values for properties of string, number & integer types can be restricted with an enum validator.
- Arrays are allowed, with all items validating against a schema normally used to validate simple properties (i.e., boolean, string, or number, schema, or a CType reference).
- Length assertions are allowed for arrays and strings.
- Maximum and minimum value assertions are allowed for numbers and integers.
It's easiest to play with the metaschema (which you can also download from https://gateway.pinata.cloud/ipfs/bafybeiah66wbkhqbqn7idkostj2iqyan2tstc4tpqt65udlhimd7hcxjyq) by validating your desired CTypes against it on https://www.jsonschemavalidator.net.

feat: enums and arrays on new ctype metaschema

---

packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.ts
packages/did/src/DidResolver/DidResolver.spec.ts
packages/types/src/DidDocumentExporter.ts

Makes all key ids on a (compliant) DID document absolute uris (i.e., starting with the DID).
See https://github.com/KILTprotocol/sdk-js/pull/734#discussion_r1149076735.

refactor!: make all key ids absolute uris on conformant did doc

---

.github/actions/cached-image-pull/action.yml
.github/workflows/devpackpublish.yml
.github/workflows/docpublish.yml
.github/workflows/npmpublish-rc.yml
.github/workflows/npmpublish.yml
.github/workflows/semantic-pull-request.yml
.github/workflows/test-node-candidate.yml
.github/workflows/tests-polkadot-deps.yml
.github/workflows/tests.yml
.nvmrc

Updates GitHub workflows to no longer use deprecated actions and features which will be retired shortly.
Run as many workflows as possible I guess.

ci: update GitHub workflows

---

packages/config/package.json
packages/config/src/ConfigService.spec.ts
packages/config/src/ConfigService.ts
packages/utils/src/SDKErrors.ts
yarn.lock

Removes unnecessary imports on the config package to make sure we don't add additional cjs imports in an esm context. 
Test sporran bundle size with this.

refactor: remove kilt dependencies from config package

---

.github/workflows/tests-polkadot-deps.yml

The polkadot dependency upgrade workflow is broken. This fixes it.

ci: fix test polkadot deps wf

---

packages/did/src/DidDetails/FullDidDetails.ts

Companion of https://github.com/KILTprotocol/kilt-node/pull/528.

feat: add `dipProvider` pallet for DID extrinsic signing

---

packages/core/src/__integrationtests__/Ctypes.spec.ts
packages/core/src/ctype/CType.chain.ts

Nests the CType in the ICTypeDetails so you can use it for credential validation without stripping its additional properties.
__Breaking:__ changes the return value of `fetchFromChain`.

refactor!: nest ctype in ICTypeDetails

---

packages/config/src/ConfigService.spec.ts
packages/config/src/ConfigService.ts
packages/core/src/ctype/CType.ts

Prints a deprecation message if CTypes following the legacy meta schema are being used.
Also adjusts the default log level in non-production environments so that these messages are actually shown.
Unit tests now started printing these deprecation messages.

feat: deprecate CType meta schema draft-01

---

tests/bundle/bundle.spec.ts
tests/integration/ErrorHandler.spec.ts
tests/integration/utils.ts

A different startup strategy is required for kilt nodes based on polkadot v0.9.43 because the CLI has changed and arguments have been renamed.
This introduces a fallback strategy if the container can't be started, and will try again using a set of arguments which should work for the new CLI.
Latest currently uses the old CLI, while latest-develop uses the new CLI. If both integration test runs succeed, this works.

test: make tests work with new kilt node cli

---

package.json
packages/asset-did/package.json
packages/augment-api/package.json
packages/chain-helpers/package.json
packages/config/package.json
packages/core/package.json
packages/did/package.json
packages/messaging/package.json
packages/sdk-js/package.json
packages/testing/package.json
packages/type-definitions/package.json
packages/type-definitions/src/types_11000.ts
packages/types/package.json
packages/utils/package.json
packages/vc-export/package.json

Companion of https://github.com/KILTprotocol/kilt-node/pull/573, based on top of https://github.com/KILTprotocol/sdk-js/pull/802. Published as `0.33.2-dip-2`.

feat: add versioning support

---

packages/did/src/Did.utils.ts
packages/did/src/DidResolver/DidResolver.spec.ts

Fixes https://github.com/KILTprotocol/ticket/issues/2568.
A light DID with encoded details that cannot be decoded to anything, is indeed an invalid DID and should be treated as such 😁😁😁

fix: include encoded details in DID validation logic

---

packages/config/src/ConfigService.spec.ts

Added // @ts-ignore 
Only values 0-6 are valid. https://github.com/vauxite-org/typescript-logging/blob/cf0d3e7d52b1da0650b16308cc3f1a56bcb95b5b/core/src/typescript/main/core/api/LogLevel.ts#L5C1-L12C10

fix: ignore out-of-range log level in ConfigService.spec.ts

---

.github/workflows/tests-polkadot-deps.yml
.github/workflows/tests.yml
.nvmrc
packages/asset-credentials/package.json
packages/augment-api/package.json
packages/chain-helpers/package.json
packages/config/package.json
packages/credentials/package.json
packages/did/package.json
packages/jsonld-suites/package.json
packages/legacy-credentials/package.json
packages/sdk-js/package.json
packages/type-definitions/package.json
packages/types/package.json
packages/utils/package.json

Require at least node v18 (maintenance), CI uses node v20 (current). Testing against v16 has moved to optional.
https://nodejs.org/en/about/previous-releases
CI should not break.

chore(deps): bump node to v18

---

packages/did/package.json
yarn.lock

See https://github.com/digitalbazaar/multikey-context/issues/5
Changes are non-breaking:
https://github.com/digitalbazaar/multikey-context/compare/v1.0.0...v2.0.0

fix: require multikey^2.0.1 as earlier versions are broken

---

tests/integration/Did.spec.ts

These tests don't behave as advertised and just test the value of a runtime constant, which makes little sense - especially when the value varies between runtimes.
Disabling them for now, we should refactor or remove later.

test: disable pointless and breaking did integration tests

---

packages/asset-credentials/src/credentials/PublicCredential.chain.ts
packages/chain-helpers/package.json
packages/chain-helpers/src/blockchain/Blockchain.ts
packages/credentials/src/V1/KiltAttestationProofV1.ts
packages/credentials/src/ctype/CType.chain.ts
tests/integration/Ctypes.spec.ts
tests/integration/PublicCredentials.spec.ts
yarn.lock

While I hot fixed the current behaviour in https://github.com/KILTprotocol/sdk-js/pull/836 to allow extrinsics submitted via dispatchAs, I think it's a better strategy for the future to build on top of on an unwrapper function that returns nested calls contained within other extrinsics that can easily be amended. E.g., we could easily add unwrapping of proxy calls to the logic here and everything still works.
Ideally, fetch a CType with it.

refactor: more flexible extrinsic unwrapping for ctype fetching

---

packages/did/src/Did.signature.spec.ts
packages/did/src/Did.signature.ts
packages/legacy-credentials/src/Credential.ts

The output of signatureFromJson and the input of verifyDidSignature were no longer aligned, making their combination quite cumbersome.

refactor: align signatureFromJson & verifyDidSignature

---

packages/credentials/src/issuer.ts
tests/bundle/bundle-test.ts

Align with VC terminology to avoid confusion. Tom suggested that instead of its goal of easing credential creation the current solution just introduces confusion and is incoherent with our goal of aligning our stack more closely with the specs and their vocabulary.
Tests have been updated.

refactor: use credentialSubject on credential constructor

---

packages/credentials/src/verifier.ts
packages/did/src/Did.signature.ts
tests/bundle/bundle-test.ts

Converts the parameters of verifyCredential & verifyPresentation to maps, which avoids having to pass empty maps when only setting config options.
Also flattens presentation verification options, so that only credential verification options are nested within them.

refactor!: verify parameters as maps

---

packages/did/src/DidResolver/DidResolver.ts
packages/types/src/DidResolver.ts

Don't require passing empty resolution options into did resolver functions.

chore: make resolution options optional

---

packages/asset-credentials/src/credentials/PublicCredential.chain.ts
packages/credentials/src/attestation/Attestation.chain.ts
packages/credentials/src/ctype/CType.chain.ts
packages/credentials/src/delegation/DelegationDecoder.ts
packages/credentials/src/presentation/Presentation.spec.ts
packages/did/src/Did.chain.ts
packages/did/src/Did.rpc.ts
packages/did/src/Did.signature.spec.ts
packages/did/src/Did.signature.ts
packages/did/src/Did.utils.ts
packages/did/src/DidDetails/DidDetails.ts
packages/did/src/DidDetails/LightDidDetails.spec.ts
packages/did/src/DidDetails/LightDidDetails.ts
packages/did/src/DidResolver/DidResolver.spec.ts
packages/did/src/DidResolver/DidResolver.ts
packages/jsonld-suites/src/suites/KiltAttestationProofV1.spec.ts
packages/jsonld-suites/src/suites/Sr25519Signature2020.spec.ts
packages/legacy-credentials/src/Credential.spec.ts
packages/types/src/Did.ts
tests/bundle/bundle-test.ts
tests/integration/Did.spec.ts
tests/testUtils/TestUtils.ts

All Ids are made absolute in Did documents.
Unit & integration tests are adjusted.

refactor!: make DidDocument ids absolute

---

packages/credentials/src/verifier.ts
tests/bundle/bundle-test.ts

Renames parameter from verifyPresentation() from `config.cTypeLoader` to `config.cTypes`. 
```
cTypes?: CTypeLoader | ICType[]
```

fix: rename cTypeLoader to cTypes on the verifyCredential

---

package.json
yarn.lock

The current version of 'testcontainer' fails on the Mac silicon.
Updating to work on test locally.
- Step 1
- Step 2
- etc.

fix: updating the testcontainer dep

---

packages/core/src/credential/Credential.ts

Checking the ctype ID in the credential to verify if matching ctype and credential ctype hash
yarn test

fix: CType ID is checked in presentation

---

packages/legacy-credentials/src/Credential.ts

Updating the verify credential to check against the credentials ctypes id against the given ctype
- Step 1
- Step 2
- etc.

fix: CType does not check credential ctype in presentation

---

.github/actions/cached-image-pull/action.yml
.github/workflows/devpackpublish.yml
.github/workflows/docpublish.yml
.github/workflows/npmpublish-rc.yml
.github/workflows/npmpublish.yml
.github/workflows/test-node-candidate.yml
.github/workflows/tests-polkadot-deps.yml
.github/workflows/tests.yml
Dockerfile

- Makes sure the `package.json` specifies `yarn` version. 
- Upgrades the used **node version**  on the `.nvmrc`  to `lts/Iron`. 
- Makes sure the **GitHub workflows** uses node version 20. 
For this following must be set: 
- `actions/checkout@v4`
- `actions/setup-node@v4` **with:**  _either_
- **node-version-file:** '`package.json`' or '`.nvmrc`' 
-  **node-version:**  `'`<Node.js version using [SemVer](https://semver.org/) or [aliases](https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule) > `'`
- `actions/download-artifact@v4`
- _optional, but done:_ `actions/cache@v4`
-  `aws-actions/configure-aws-credentials@v4`
-  `aws-actions/amazon-ecr-login@v2`
- Makes sure the **Dockerfiles** also use the node version 20. 
This means that the following must be set: 
- `FROM …

chore: update to node v20 

---

packages/sdk-js/src/DidHelpers/common.ts
packages/sdk-js/src/DidHelpers/index.ts
packages/sdk-js/src/DidHelpers/w3names.spec.ts
packages/sdk-js/src/DidHelpers/w3names.ts
tests/integration/didHelpers.spec.ts

Implements [`claimWeb3Name`](https://github.com/KILTprotocol/sdk-js/commit/e24a16711aca56d56849269cfe74eade1abc606e) & [`releaseWeb3Name`](https://github.com/KILTprotocol/sdk-js/commit/9f34954ee2725696beac72102d0d7e7ccb879353) and adds integration tests for both.
Also fixes a bug in matching module errors.
Rudimentary unit test and basic integration tests are included.

feat: claim and release w3n helpers

---

packages/sdk-js/src/DidHelpers/index.ts
packages/sdk-js/src/DidHelpers/service.spec.ts
tests/integration/didHelpers.spec.ts

Adds unit- and integration tests for `addService` & `removeService`.
Seriously?

test: services unit & integration tests

---

packages/sdk-js/src/DidHelpers/setVerificationMethod.ts

I reviewed the setVerificationMethod implementation and found two issues that need fixing.
I'm addressing them here.

fix: setVerificationMethod extrinsics and logic

---

packages/sdk-js/src/DidHelpers/deactivateDid.spec.ts
packages/sdk-js/src/DidHelpers/deactivateDid.ts
packages/sdk-js/src/DidHelpers/index.ts
tests/integration/didHelpers.spec.ts

Implements the [`deactivateDid`](https://github.com/KILTprotocol/sdk-js/commit/2edcb7da763fa754d6be715ff9f90b141b11131a) function and adds unit & integration tests.
We didn't have an interface specced out for it, but I think it's pretty straightforward. It just deactivates the DID whose DID document is passed.
Basic unit & integration tests are included.

feat: implement deactivateDid

---

packages/sdk-js/src/DidHelpers/checkResult.ts
packages/sdk-js/src/DidHelpers/interfaces.ts
packages/sdk-js/src/DidHelpers/transact.spec.ts

fixes https://github.com/KILTprotocol/ticket/issues/3529
Adds `toJSON` implementation to the `TransactionResult` objects that include a block number.
Another way to solve the serialization issue is to change the block number type to `string`.

fix: transaction result serialization

---

packages/credentials/src/V1/KiltAttestationProofV1.ts
packages/credentials/src/holder.ts
packages/credentials/src/interfaces.ts
packages/credentials/src/issuer.ts
packages/credentials/src/verifier.ts
tests/bundle/bundle-test.ts
tests/integration/didHelpers.spec.ts

- breaking: unnest selective disclosure parameters dc8d45865ca7d070f3d38a2451c16aff960a9b46
- breaking: fully switch to using named parameters on credentials functions 3c17ace73089be9b74458d6709881d576b33115b
- non-breaking: allow passing key pairs & signers as submitter parameter on `issue()` bcd882f8e5c10c0dc0d74946851072da1fd842aa
- Actually trying the new interfaces could be done on the beta that is to be released
- Tests for new features are yet to be written

refactor!: integrate feedback on alpha release

---

packages/asset-credentials/package.json
packages/chain-helpers/package.json
packages/config/package.json
packages/credentials/package.json
packages/credentials/src/V1/KiltAttestationProofV1.ts
packages/did/package.json
packages/did/src/Did.rpc.ts
packages/jsonld-suites/package.json
packages/legacy-credentials/package.json
packages/sdk-js/package.json
packages/types/src/Address.ts
packages/utils/package.json
packages/utils/src/Crypto.ts
packages/utils/src/Signers.ts
yarn.lock

Set polkadot dependencies as peer dependencies on sub-packages, which should help avoid versioning chaos.
For convenience the sdk-js package still marks all polkadot-js packages as direct dependents.

chore(deps): polkadot-js as peer dependency
