KILTprotocol/sdk-js

src/attestedclaim/AttestedClaim.ts
src/requestforattestation/RequestForAttestation.ts

fix: claimowner not included in claimhashtree

---

src/attestation/Attestation.chain.ts
src/attestation/Attestation.ts
src/blockchain/TxStatus.ts
src/ctype/CType.chain.ts
src/delegation/Delegation.ts
src/delegation/DelegationDecoder.ts
src/delegation/DelegationNode.chain.ts
src/delegation/DelegationNode.ts
src/delegation/DelegationRootNode.chain.ts
src/delegation/DelegationRootNode.ts
src/did/Did.chain.ts
src/did/Did.spec.ts
src/did/Did.ts
src/did/Did.utils.ts
src/errorhandling/ErrorHandler.ts
src/identity/PublicIdentity.spec.ts
src/identity/PublicIdentity.ts

This PR switches undefined return types to null, where applicable
Run tests and build library

feat: switch undefined to null

---

src/attestedclaim/AttestedClaim.ts

If you'd like to see how the doc looks like:  
Run `npm run build:docs`. This generates the doc at `sdk-js/docs/api`.
Open the so-generated files in your browser: `sdk-js/docs/api/classes/attestedclaim.attestedclaim-1.html`.

Mn 176 - doc public methods AttestedClaim

---

src/attestation/Attestation.ts
src/attestedclaim/AttestedClaim.ts
src/identity/Identity.ts
src/identity/PublicIdentity.ts
src/requestforattestation/RequestForAttestation.ts

Created a new branch with the latest develop. 
reverting some documentation on the latest develop.
Documentation

Docs: Reverted documentation changes according to meet standard

---

src/ctype/CType.spec.ts

Expanded the test suite to reach code coverage
Yarn Test
Test Suites: 1 skipped, 17 passed, 17 of 18 total
Tests:       2 skipped, 50 passed, 52 total

Test: expanded test suite

---

src/index.ts

reverted unintentional change to index.ts which threw prettier errors.

chore: fix prettier error

---

src/types/Terms.ts

Needed to fix minor change in types from the Quote
yarn test

fix: changed the iterms to fix types

---

docs/example.ts

The example was broken and should be fixed now.
```
ts-node docs/example.ts
```

fix: example

---

src/messaging/Message.spec.ts
src/quote/Quote.spec.ts
src/quote/Quote.ts

chore: updating the naming

---

src/balance/Balance.chain.ts

As always `yarn test && yarn test:integration`.

fix: leaked subscription

---

src/actor/Attester.spec.ts
src/actor/Verifier.spec.ts
src/actor/Verifier.ts
src/attestation/Attestation.ts
src/blockchainApiConnection/__mocks__/BlockchainApiConnection.ts

test: fix mocked types

---

src/attestation/Attestation.spec.ts
src/ctype/CType.ts

Fixes Attestation.ts uncovered functions
Related to: https://github.com/KILTprotocol/ticket/issues/606

test: attestation typeguard test

---

src/attestation/Attestation.spec.ts
src/attestation/Attestation.ts
src/attestedclaim/AttestedClaim.spec.ts

Fixes AttestedClaim.ts uncovered functions
Related to: https://github.com/KILTprotocol/ticket/issues/606

test: attested claim coverage

---

src/ctype/CType.spec.ts
src/ctype/CTypeMetadata.spec.ts

Fixes CType.ts uncovered functions
Related to: https://github.com/KILTprotocol/ticket/issues/606

test: ctype coverage

---

src/balance/Balance.chain.ts

docs: outdated denomination

---

.github/workflows/devpackpublish.yml
.github/workflows/npmpublish.yml
.npmignore
.npmrc
package.json

Please include a summary of the changes provided with this pull request and which issue has been fixed. 
Please also provide some context if necessary.
- Step 1
- Step 2
- etc.

feat: publish prerelease to npm

---

packages/actors_api/src/actors/Attester.ts
packages/core/src/delegation/DelegationNode.utils.ts
packages/core/src/delegation/index.ts
packages/core/src/errorhandling/ExtrinsicError.ts
packages/core/src/index.ts

Added the traversal steps checker to the delegation utils 
N/A

refactor: Moved delegation parent steps checker to delegation Utils

---

packages/core/src/delegation/DelegationNode.ts

Reverts the hot fix I included to work with the previous rendering of max_depth
integration tests once https://github.com/KILTprotocol/mashnet-node/pull/123 is merged

refactor: nodeside fix to max_depth count

---

docs/getting-started.md

Using the example mnemonic, the addresses generated are different than the one in the example. I updated those. Plus, minor changes.

doc: fix minor language stuff + update claimer and attester addresses

---

package.json
packages/actors_api/package.json
packages/chain-helpers/package.json
packages/config/package.json
packages/core/package.json
packages/core/src/delegation/DelegationRootNode.chain.ts
packages/messaging/package.json
packages/sdk-js/README.md
packages/sdk-js/package.json
packages/types/package.json
packages/utils/package.json
packages/vc-export/package.json

fix: devpublish

---

.github/workflows/devpackpublish.yml

fix: gh workflow syntax

---

package.json
packages/actors_api/package.json
packages/chain-helpers/package.json
packages/config/package.json
packages/core/package.json
packages/messaging/package.json
packages/sdk-js/package.json
packages/types/package.json
packages/utils/package.json
packages/vc-export/package.json

chore: bump version

---

.github/workflows/tests.yml

Please include a summary of the changes provided with this pull request and which issue has been fixed. 
Please also provide some context if necessary.
- Step 1
- Step 2
- etc.

chore: don't fail workflow on dev error

---

package.json
packages/actors_api/package.json
packages/chain-helpers/package.json
packages/config/package.json
packages/core/package.json
packages/messaging/package.json
packages/sdk-js/package.json
packages/types/package.json
packages/utils/package.json
packages/vc-export/README.md
packages/vc-export/package.json
packages/vc-export/src/index.ts
packages/vc-export/src/presentationUtils.ts
packages/vc-export/src/vc-js/context/context.json
packages/vc-export/src/vc-js/suites/KiltAbstractSuite.ts

- Improves documentation
- Adds possibility to create presentations with all attributes
- fixes type export
- fixes kilt VC context

fix: vc-export documentation & exports

---

packages/did/README.md

Fixes styling in the README.md of the did package

chore: fix styling

---

docs/getting-started.md

The imports as written in the getting-started guide were not working.
The getting-started.ts file was already updated.

fix: wrong kilt imports in getting-started.md

---

packages/did/src/Did.chain.ts

This PR improves the way a DID is checked for its deletion status, fixing a problem that was occurring if multiple requests were fired at the same time.

fix: improve DID deletion status querying function

---

packages/messaging/src/Message.ts

fix: minor spelling change

---

packages/core/src/balance/Balance.chain.ts

The doc was hard to understand.

doc: fix transfer example

---

packages/core/src/__integrationtests__/Attestation.spec.ts
packages/core/src/__integrationtests__/Did.spec.ts
packages/did/src/Did.chain.ts

fix: raw DID signature encoding

---

.github/workflows/devpackpublish.yml
.github/workflows/docpublish.yml
.github/workflows/npmpublish-rc.yml

Fixes https://github.com/KILTprotocol/ticket/issues/1858 and fixes https://github.com/KILTprotocol/ticket/issues/1877.
On the side, it also deletes seemingly outdated dispatched upon dev releases, which are always failing anyway.

chore: add release candidate workflow

---

packages/utils/src/Crypto.spec.ts
packages/utils/src/Crypto.ts

Does what's in the name.
Not required

chore: remove symmetric crypto

---

.github/workflows/devpackpublish.yml

https://github.com/KILTprotocol/sdk-js/runs/5554031564?check_suite_focus=true was failing. I guess this would fix this issue, as suggested?

fix: dev release pipeline

---

.github/workflows/tests-polkadot-deps.yml
packages/sdk-js/README.md
packages/testing/package.json
packages/testing/src/mocks/metadata/spiritnet.json

Just some smaller fixes on the scheduled workflow.
1. Update the spiritnet metadata before running tests. This ensures that type encoding and other assumptions still match what is going on on the mainnet.
2. Small fix to improve caching
3. Upload `yarn.lock` to provide a resource for investigation if build fails
4. Commit latest version of spiritnet metadata so that all other tests are representative of current chain state.
See [run](https://github.com/KILTprotocol/sdk-js/actions/runs/2022027259) triggered by [cafe05f](https://github.com/KILTprotocol/sdk-js/pull/507/commits/cafe05fa45e896ca6e14c6edb1db02e93dc23b8f)

ci: improvements for scheduled workflow

---

.github/workflows/tests-polkadot-deps.yml
docker-compose.yml
docs/contribution-guide.md
packages/chain-helpers/src/blockchainApiConnection/BlockchainApiConnection.ts
packages/core/src/claim/Claim.utils.ts
packages/core/src/ctype/CTypeNested.spec.ts
packages/core/src/delegation/DelegationNode.spec.ts
packages/core/src/delegation/DelegationNode.ts
packages/core/src/delegation/DelegationNode.utils.ts
packages/messaging/src/Message.utils.spec.ts
packages/sdk-js/README.md
packages/types/src/DidDocumentExporter.ts
packages/types/src/DidResolver.ts
packages/types/src/Keystore.ts
packages/utils/src/Crypto.ts
packages/vc-export/src/types.ts

There were some spelling mistakes in the codebase
Check with a dictionary

chore: fixed spelling

---

packages/did/src/DidDetails/LightDidDetails.utils.ts

The utils for light DIDs are using a type that makes TS think values are always undefined. This PR fixes that.

fix: light DID serialization types

---

package.json
packages/chain-helpers/package.json
packages/core/package.json
packages/messaging/package.json
packages/testing/package.json
packages/types/package.json
packages/vc-export/package.json
yarn.lock

I went through dependencies with `depcheck` and removed what seemed unused.
If the tests don't break I think we're good.

chore(deps): remove unused dependencies

---

packages/core/src/delegation/DelegationNode.chain.ts
packages/core/src/delegation/DelegationNode.ts
packages/did/src/Did.chain.ts
packages/did/src/Did.utils.ts
packages/did/src/DidBatcher/DidBatchBuilder.spec.ts
packages/did/src/DidBatcher/FullDidBuilder.utils.ts
packages/did/src/DidBatcher/FullDidUpdateBuilder.ts
packages/did/src/DidLinks/AccountLinks.chain.ts
packages/types/src/DidDetails.ts

Some suggestions for further improvements of #582. I recommend reading my comments in proper order on the conversations tab first.

feat: remove Capitalize, Lowercase, TypedValue

---

packages/types/src/Address.ts
tests/bundle-test.ts

The refactoring accumulated changes to the bundle tests and stopped being an example of what application developers might write. I try to bring it back to its senses.

fix: more realistic bundle tests

---

packages/did/src/Did.chain.ts
packages/did/src/DidDetails/DidDetails.ts
packages/did/src/DidDetails/LightDidDetails.spec.ts
packages/did/src/DidLinks/AccountLinks.chain.ts
packages/did/src/DidLinks/Web3Names.chain.ts
packages/testing/src/TestUtils.ts
packages/vc-export/src/verificationUtils.ts
tests/bundle-test.ts

The comments were a bit lax in the proper capitalization of the term `DID`.

fix: capitalization of DID

---

packages/did/src/Did.chain.ts
packages/did/src/Did.utils.ts
packages/did/src/DidDetails/DidDetails.ts
packages/did/src/DidDetails/FullDidDetails.ts
packages/messaging/src/Message.ts
packages/testing/src/TestUtils.ts

The functions seem to bring no value, and even their names are longer

feat!: replace function calls with map lookups

---

packages/did/src/Did.chain.ts
packages/did/src/DidDetails/FullDidDetails.spec.ts
packages/did/src/DidDocumentExporter/DidDocumentExporter.spec.ts
packages/did/src/DidResolver/DidResolver.spec.ts

I have addressed the outcomes of my review in June

feat: improved Did.chain.ts

---

packages/core/src/quote/Quote.ts
packages/messaging/src/Message.spec.ts

Check the verification result before continuing

fix: verifyDidSignature check

---

packages/did/src/DidResolver/DidResolver.spec.ts
packages/did/src/DidResolver/DidResolver.ts
packages/types/src/DidResolver.ts

There was much duplication of code, also the endpoints and keys were not getting the latest values.

feat: streamline resolution of DIDs, keys, endpoints

---

packages/types/src/Credential.ts

Export two new types as specified in the spec https://github.com/KILTprotocol/spec-KiltPublishedCredentialCollectionV1.

feat: add KiltPublishedCredentialV1 and KiltPublishedCredentialCollectionV1 types

---

packages/types/src/Credential.ts

Based on the open PR https://github.com/KILTprotocol/spec-KiltPublishedCredentialCollectionV1/pull/1

fix: update type of published credential and export constant

---

packages/did/src/Did.chain.ts
packages/did/src/Did.signature.spec.ts
packages/did/src/DidDetails/DidDetails.ts
packages/did/src/DidDetails/FullDidDetails.ts
packages/testing/src/TestUtils.ts
packages/types/src/CryptoCallbacks.ts
tests/bundle-test.ts

This PR changes things, which were coming up as feedback to the new callbacks.
- Tests

feat!: callback feedback

---

packages/augment-api/package.json
packages/core/package.json
packages/type-definitions/package.json
packages/type-definitions/src/index.ts
packages/type-definitions/src/rpc.ts
packages/type-definitions/src/runtime.ts
packages/type-definitions/src/types_10.ts
packages/type-definitions/src/types_10720.ts
packages/type-definitions/src/types_10900.ts
packages/type-definitions/src/types_12.ts
packages/type-definitions/src/types_17.ts
packages/type-definitions/src/types_18.ts
packages/type-definitions/src/types_19.ts
packages/type-definitions/src/types_20.ts
packages/type-definitions/src/types_21.ts
packages/type-definitions/src/types_23.ts
packages/type-definitions/src/types_25.ts
packages/type-definitions/src/types_2700.ts
packages/type-definitions/src/types_8.ts
packages/type-definitions/src/types_9.ts
packages/type-definitions/tsconfig.build.json
packages/type-definitions/tsconfig.esm.json
tsconfig.docs.json
tsconfig.json
yarn.lock

Move https://github.com/KILTprotocol/type-definitions over to the monorepo.

chore: add type definitions inside the monorepo

---

packages/types/src/CryptoCallbacks.ts
packages/types/src/DidDocumentExporter.ts

fixes descriptions of callbacks that did not match their current state

chore: update callback docstrings

---

jest.config.js
packages/core/src/credential/Credential.ts
packages/utils/src/Crypto.ts

- don't check coverage for type-definitions package
- don't add challenge property to DidSignature if no challenge is given
- explicit string normalisation (NFC) on encodeObjAsStr

fix: various minor fixes

---

packages/augment-api/src/types.ts
packages/did/src/DidDocumentExporter/README.md
packages/vc-export/README.md

fixing outdated README examples and fixing the export of types from the augment-api package.

fix: 0.30.0-rc.1 issues

---

docs/package.json
packages/augment-api/package.json
packages/chain-helpers/package.json
packages/core/package.json
packages/did/package.json
packages/messaging/package.json
packages/testing/package.json
packages/types/package.json
packages/utils/package.json
packages/vc-export/package.json
yarn.lock

Fixes minor incoherences in dependencies that are shared between multiple sub-packages.

fix: align dependency versions

---

yarn.lock

chore: bump some deps

---

packages/type-definitions/src/index.ts
packages/type-definitions/src/runtime/dipSender.ts
packages/type-definitions/src/types_11000.ts

Companion of https://github.com/KILTprotocol/kilt-node/pull/492.

feat: DID merkle proofs

---

packages/type-definitions/src/runtime/dipProvider.ts
packages/type-definitions/src/types_11000.ts

Companion of https://github.com/KILTprotocol/kilt-node/pull/525.

chore: update types for additional linked info

---

packages/utils/src/SDKErrors.ts

BREAKING CHANGE: This PR removes error types that require users to update their code.

refactor!: remove error types

---

package.json
packages/asset-did/package.json
packages/augment-api/package.json
packages/chain-helpers/package.json
packages/config/package.json
packages/core/package.json
packages/did/package.json
packages/messaging/package.json
packages/sdk-js/package.json
packages/testing/package.json
packages/type-definitions/package.json
packages/type-definitions/src/runtime/dipProvider.ts
packages/type-definitions/src/types_11000.ts
packages/types/package.json
packages/utils/package.json
packages/vc-export/package.json

Companion of https://github.com/KILTprotocol/kilt-node/pull/572. It will be changed if anything relevant changes in the node PR, and new npm versions with the `dip` tag will be released.

feat: error management

---

packages/did/package.json
yarn.lock

See https://github.com/digitalbazaar/security-context/issues/4

chore(deps): bump @digitalbazaar/security-context

---

packages/did/src/Did.signature.spec.ts
packages/did/src/Did.signature.ts
packages/legacy-credentials/src/Credential.spec.ts
packages/legacy-credentials/src/Credential.ts

The simpler solution for the issue at hand seems to be to refactor Did.signature functions and dependents to use `resolve()` instead of `dereference()`, which can easily be done. Resolve provides the more unambiguous interface, because it does not deal with different did document representations, and thus is much more straightforward to use. 

refactor!: align all functions to consume didResolver

---

packages/sdk-js/src/DidHelpers/service.ts

Fixes https://github.com/KILTprotocol/ticket/issues/3516
Fixes https://github.com/KILTprotocol/ticket/issues/3374

feat: add service methods

---

tests/integration/didHelpers.spec.ts

Adds an integration test to register a CType using `transact`.

test: transact integration test

---

packages/credentials/src/holder.ts
packages/credentials/src/issuer.ts
packages/sdk-js/src/index.ts

- Removes signAndSubmitTx
- Updates some outdated docstrings

refactor!: update sdk surface

---

packages/asset-credentials/package.json
packages/chain-helpers/package.json
packages/credentials/package.json
packages/credentials/src/proofs/DataIntegrity.ts
packages/did/package.json
packages/jsonld-suites/package.json
packages/legacy-credentials/package.json
packages/sdk-js/package.json
packages/utils/package.json
yarn.lock

chore(deps): update our packages to latest rc
